use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/categories",
        "merchandise",
        "categories.management.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/categories",
        "merchandise",
        "categories.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/categories/{categoryId}",
        "merchandise",
        "categories.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/catalog/categories/{categoryId}",
        "merchandise",
        "categories.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/products",
        "merchandise",
        "products.management.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/products",
        "merchandise",
        "products.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/products/{productId}",
        "merchandise",
        "products.management.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/products/{productId}",
        "merchandise",
        "products.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/catalog/products/{productId}",
        "merchandise",
        "products.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/products/{productId}/publish",
        "merchandise",
        "products.publish",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/products/{productId}/archive",
        "merchandise",
        "products.archive",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/skus",
        "merchandise",
        "skus.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/skus",
        "merchandise",
        "skus.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/skus/{skuId}",
        "merchandise",
        "skus.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/catalog/skus/{skuId}",
        "merchandise",
        "skus.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/attributes",
        "merchandise",
        "attributes.management.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/attributes",
        "merchandise",
        "attributes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/category_attributes",
        "merchandise",
        "categoryAttributes.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/category_attributes",
        "merchandise",
        "categoryAttributes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/category_attributes/{bindingId}",
        "merchandise",
        "categoryAttributes.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/catalog/category_attributes/{bindingId}",
        "merchandise",
        "categoryAttributes.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/price_lists",
        "merchandise",
        "priceLists.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/price_lists",
        "merchandise",
        "priceLists.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/price_lists/{priceListId}",
        "merchandise",
        "priceLists.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/media",
        "merchandise",
        "media.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/media",
        "merchandise",
        "media.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/media/{mediaId}",
        "merchandise",
        "media.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/catalog/media/{mediaId}",
        "merchandise",
        "media.delete",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
