schema_version: 1
kind: sdkwork.database.schema
database_role: authoritative-server
module_id: merchandise
contract_version: 1.0.0
owner_team: merchandise-platform
compliance_level: L2
engines:
  - postgres
table_prefix: commerce_
tables:
  - name: commerce_product_spu
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_sku
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_category
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_attribute
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_attribute_value
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_price_list
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_currency
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_category_translation
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_attribute_translation
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_attribute_value_translation
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_category_attribute
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_spu_translation
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_spu_attribute
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_sku_attribute
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_sku_translation
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_product_media
    lifecycle_status: active
    owner: merchandise-platform
  - name: commerce_price_list_item
    lifecycle_status: active
    owner: merchandise-platform
