[package]
rust-version.workspace = true
name = "sdkwork-api-merchandise-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-merchandise application HTTP plane."


[lints]
workspace = true
[lib]
name = "sdkwork_api_merchandise_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork_merchandise_service_host.workspace = true
sdkwork-routes-merchandise-backend-api.workspace = true
